# Generated by Django 4.1.7 on 2023-05-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import university_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university_app', '0002_student_user_teacher_user_alter_teacher_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=university_app.models.get_datetime, editable=False, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=university_app.models.get_datetime, validators=[university_app.models.validate_time], verbose_name='modified')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'head teacher',
                'verbose_name_plural': 'head teachers',
                'db_table': 'headteacher',
                'ordering': ['full_name'],
            },
        ),
    ]
