# Generated by Django 4.1.7 on 2023-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_delete_headteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(blank=True, choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='mark'),
        ),
    ]
